### ISSUE TITLE
Excessive CPU usage on certain pages

### ISSUE THREAD

**Issue by christian-bromann** [saucelabs/docusaurus-theme-github-codeblock#5]
## Description

Navigating to a page like https://docs.staging.saucelabs.net/testrunner-toolkit/configuration causes excessive CPU usage (150% in my case).
Other pages like https://docs.staging.saucelabs.net/testrunner-toolkit/running-tests do not exhibit such an issue.

I spoke to @spider-sauce earlier and he thinks it could be related to the github references plugin.

## To Reproduce

Just navigate to a page like https://docs.staging.saucelabs.net/testrunner-toolkit/configuration and observe your browser process CPU usage.

## Expected Behavior

CPU usage is constant after page has finished loading.

## Actual Behavior

Excessive CPU usage after page has loaded and does not go down.

* OS: macOS Catalina
* Browser version: Firefox 84

**Comment by spider-sauce** [comment]
@christian-bromann I can confirm that after the page loads it seems to infinitely fetch the GH references, in this case the config `.yml` files.

<img width="973" alt="Screen Shot 2021-01-19 at 9 48 21 AM" src="https://user-images.githubusercontent.com/45496368/105073514-039b9e80-5a3c-11eb-8eb7-322d618860ec.png">

**Comment by christian-bromann** [comment]
Fixed with https://github.com/saucelabs/docusaurus-theme-github-codeblock/commit/daae1f2228f5269804ca6962b775a2ccb1011e83
