### ISSUE TITLE
Deprecated dependencies and error

### ISSUE THREAD

**Issue by lkrell** [saucelabs/docusaurus-theme-github-codeblock#6]
Hello! I would love to use this plugin, but hitting an UnhandledPromiseRejectionWarning error, which only pops up when using this plugin. It installs and does run perfectly, generates nicely, but the error keeps popping up and warns about deprecation. Some of the dependency packages have deprecations, maybe those need updates? Thanks!

```
(node:19682) UnhandledPromiseRejectionWarning: Error: Minified React error #301; visit https://reactjs.org/docs/error-decoder.html?invariant=301 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
(Use `node --trace-warnings ...` to show where the warning was created)
(node:19682) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:19682) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I'm on Docusaurus v2 2.0.0-70.

**Comment by christian-bromann** [comment]
@lkrell thanks for filing the issue, can you provide somehow a reproducible example. I couldn't really get this error to appear on my side.

**Comment by lkrell** [comment]
Sure! I am using Docusaurus v2 with the following plugins/packages in my package.json on a Mac Pro running Catalina:

```
"dependencies": {
    "@babel/plugin-transform-modules-commonjs": "^7.12.1",
    "@docusaurus/core": "^2.0.0-alpha.70",
    "@docusaurus/plugin-google-analytics": "^2.0.0-alpha.70",
    "@docusaurus/preset-classic": "2.0.0-alpha.70",
    "@docusaurus/theme-common": "^2.0.0-alpha.70",
    "@mdx-js/react": "^1.6.21",
    "@saucelabs/theme-github-codeblock": "0.0.3",
    "clsx": "^1.1.1",
    "mermaid": "^8.9.0",
    "plugin-image-zoom": "github:ataft/plugin-image-zoom",
    "react": "^16.8.4",
    "react-dom": "^16.8.4"
  },
```

I'm working in a branch with your package added. It works beautifully! I love it! But it keeps throwing that deprecation error. Our github master does not have the package, no error. I tried digging in, tried forking to see if I updated packages if that would help. Pretty confused why it pops up too. It only starts popping up with this package installed. 

I tried an `npm install` and `npm update`, still get it. I wondered if it was just packages colliding. I did check for deprecated versions and had this list pop up, most are used in this package:

![image](https://user-images.githubusercontent.com/76010626/106766754-c6203f00-65ff-11eb-9a25-0eb832957858.png)

**Comment by christian-bromann** [comment]
Mhm .. weird because this packages has [no dependencies](https://github.com/saucelabs/docusaurus-theme-github-codeblock/blob/main/package.json#L37)

**Comment by lkrell** [comment]
Definitely weird! I'll do a full clear and try again. Maybe something on my system hanging out after testing other things causing the issue. I'll dig deeper on this side and check. Thanks!

**Comment by lkrell** [comment]
Well I searched and tested and never found the issue. So seems it was caused by other files on my local. Sorry about that! The plugin continues to work beautifully! Feel free to close, and thanks for creating this plugin @christian-bromann !
