### ISSUE TITLE
Support for Docusaurus 3.0

### ISSUE THREAD

**Issue by mariuszkrzaczkowski** [saucelabs/docusaurus-theme-github-codeblock#88]
Docusaurus yesterday released 3.0 which includes support for react 18. I tried to update but the plugin doesn't work

Do you plan to release an update which will support docusuarus 3?

![image](https://github.com/saucelabs/docusaurus-theme-github-codeblock/assets/10198654/a6603586-1126-416c-8401-1e1397b70c77)

![image](https://github.com/saucelabs/docusaurus-theme-github-codeblock/assets/10198654/d0d747fd-9f80-4beb-8d65-7ebb8e1ca55d)

**Comment by diemol** [comment]
Absolutely. We would need help, though. Do you know what is required to upgrade this plugin? Do you know if upgraded plugins are backwards compatible with Docusaurus v2?

**Comment by mariuszkrzaczkowski** [comment]
> Do you know what is required to upgrade this plugin? 

no, I just saw the documentation of what the problems might be
https://docusaurus.io/docs/migration/v3
https://docusaurus.io/blog/preparing-your-site-for-docusaurus-v3

>Do you know if upgraded plugins are backwards compatible with Docusaurus v2?

yes, example:
https://github.com/easyops-cn/docusaurus-search-local
https://github.com/rohit-gohri/redocusaurus

**Comment by diemol** [comment]
Would you be willing to help us migrate it to v3?

**Comment by mariuszkrzaczkowski** [comment]
I don't know TypeScript, but I can try it in my free time, there is probably a problem with updating MDX v3.0+ or TypeScript v5.0+

**Comment by gtnardy** [comment]
up 🙏

**Comment by diemol** [comment]
Thanks @mariuszkrzaczkowski!

@gtnardy would you be up to help us a bit with this?

**Comment by christian-bromann** [comment]
@diemol I have just published support for v3 in my fork of this package: https://github.com/christian-bromann/docusaurus-theme-github-codeblock. I hope this helps migrating this.

**Comment by diemol** [comment]
Thanks @christian-bromann!!

@mariuszkrzaczkowski maybe you can check the fork and give us a hand?

**Comment by monica-m-ps** [comment]
Hello. I am also facing the same issue. I recently upgraded to v3. I have a lot of GitHub code to display. This seems to be a blocker 😢

**Comment by mariuszkrzaczkowski** [comment]
> Thanks @christian-bromann!!
> 
> @mariuszkrzaczkowski maybe you can check the fork and give us a hand?

doesn't work for https://github.com/christian-bromann/docusaurus-theme-github-codeblock/issues/136
there is some other problem

**Comment by monica-m-ps** [comment]
@mariuszkrzaczkowski Were you able to troubleshoot? I can try digging into your branch if you're still blocked. I had faced loads of bugs when upgrading to 3.x.x. Let me know. 👍🏻

**Comment by mariuszkrzaczkowski** [comment]
unfortunately it still doesn't work
https://github.com/YetiForceCompany/YetiForceDoc

**Comment by monica-m-ps** [comment]
Ok I'll see what's wrong. Give me this weekend. Will get back to you.

**Comment by Dr-Electron** [comment]
Any updates on this?

**Comment by monica-m-ps** [comment]
Hello. Sorry to intervene but since I commented on this thread and got notified, 
@mariuszkrzaczkowski: I emailed you sometime back (on the email ID listed on your GitHub profile) to identify the issue, instead of spamming here. Please let me know if you received it.

Also, for others running into this issue, if it helps, I faced the same issue and was unable to render my GitHub code from another repo to my documentation repo that's running on Docusaurus 3.x.x. I first ensured Docusaurus 3.x.x was correctly installed and all breaking changes are addressed. Also, I migrated my .md files to .mdx as mentioned here https://docusaurus.io/blog/preparing-your-site-for-docusaurus-v3#preparing-content-for-mdx-v3.

With this plugin, I was getting errors related to CommonJS and ES Modules and they are well explained in the Docusaurus post https://docusaurus.io/blog/preparing-your-site-for-docusaurus-v3#mdx-plugins. 

After running into errors, I fixed the CommonJS ones and this plugin works just fine for me.

**Comment by mariuszkrzaczkowski** [comment]
Unfortunately, after several attempts, the launch fails and I was unable to start it. Migration to version 3.2.1 went without problems, but the extension does not work

![image](https://github.com/saucelabs/docusaurus-theme-github-codeblock/assets/10198654/b18d31de-e753-4595-912d-35ece0f55ba6)

![image](https://github.com/saucelabs/docusaurus-theme-github-codeblock/assets/10198654/abe3c7fd-95fa-4b5e-8612-f3107c719d52)

**Comment by sciotta** [comment]
Any updates on this?

**Comment by diemol** [comment]
@sciotta would you like to help us fix this? There is a fork where it got fixed. Maybe you can contribute?
Check the comments above. Thanks!

**Comment by gtnardy** [comment]
Hey, I pushed a PR that I found a fix doing a really small change to support docusaurus 3.0: https://github.com/saucelabs/docusaurus-theme-github-codeblock/pull/151

Review and more tests would be appreciated 🙏

**Comment by RoiArthurB** [comment]
@gtnardy Works perfectly for my project working over +500 files files :ok_hand: 

@diemol I guess you can merge it and release a new package version :D

**Comment by diemol** [comment]
Thank you, @gtnardy! I just released 0.3.0.
